### ISSUE TITLE
Change Quality of Video with 1 url.

### ISSUE THREAD

**Issue by kuldeep13990** [depaba/JDPlayer#2]
I appreciate our work but i think if you add custom xib as overlay view than anyone can change controls easily, it difficult to change the control position programatically.

(void)videoPlayer:(JDPlayer *)videoPlayer didVideoQualityButtonPressed:(JDVideoModel *)videoModel;
in above method i think i need to pass low quality url to change quality?

**Comment by letqingbin** [comment]
Q1:  you can fork the project and then add your custom xib, cheers.

Q2: yeah,you're right, change to low quality url, just like the example 
    (void)videoPlayer:(JDPlayer*)videoPlayer didPlayToEnd:(JDVideoModel *)videoModel
in JDViewController.

**Comment by kuldeep13990** [comment]
@depaba , my app is video app, like many of the user upload unlimited vide on server, so i can't upload video with different quality, i have only 1 video url.

so is is  possible to change quality with 1 video url?

**Comment by letqingbin** [comment]
it's not possible to do that using avplayer, maybe you can try ffmpeg.
ffmpeg can solve your problem.
