### ISSUE TITLE
Doesn't play youtube videos

### ISSUE THREAD

**Issue by RajChanchal** [depaba/JDPlayer#4]
Nice layout. But it doesn't seem to play youtube videos. I tried in putting in a youtube video link in the domo project.

**Comment by letqingbin** [comment]
“assetWithURL: is often, but not always, used with a URL that points to a file already on the device, often within the bundle. If you are using an external URL, such as one on the internet, the url must resolve to a video that is in a format that the AVPlayer can understand. A URL to a YouTube web page will not work. In general, you can't play a YouTube video in AVPlayer”
refer from:
http://stackoverflow.com/questions/25475955/ios-avplayer-wont-play
