### ISSUE TITLE
Support format

### ISSUE THREAD

**Issue by ghost** [depaba/JDPlayer#5]
What are the supported formats for this framework?

**Comment by letqingbin** [comment]
@LazyScream 
JDPlayer is based on AVPlayer , so it's obviously that JDPlayer can support mp4/WMV/AVI/RMVB and so on;
cheers!!

**Comment by ghost** [comment]
ok thx 
do you know how to support p2p 、rtsm？

**Comment by letqingbin** [comment]
@LazyScream 
You can try ffmpeg.
