### ISSUE TITLE
Http live Streaming Vedio play Very Slow

### ISSUE THREAD

**Issue by Devloperios** [depaba/JDPlayer#7]
Hello,

  i Have Used JdPlayer For Live Streaming , but it Should take a long Time To start a vedio.
  First i start a vedio play it take a very long time.

 Anyone please suggest best Solution for Live Streaming vedio play.

help me for those!!!!

**Comment by letqingbin** [comment]
JDPlayer is a wrapper for AVPlayer, so it's noting to about your video.
can you provide me something to debug such as URL or video?

At 2018-08-15 21:34:23, "Devloperios" <notifications@github.com> wrote:


Hello,

i Have Used JdPlayer For Live Streaming , but it Should take a long Time To start a vedio.
First i start a vedio play it take a very long time.

Anyone please suggest best Solution for Live Streaming vedio play.

help me for those!!!!

**Comment by Devloperios** [comment]
I have checked Live Streaming video Url

http://media6.smc-host.com:1935/ctvchannel.tv/ctv.smil/playlist.m3u8

http://nodeb.gocaster.net:1935/CGL/_definst_/mp4:TODAYFM_TEST2/stream.m3u8

**Comment by letqingbin** [comment]
@Devloperios
 I had tested the first m3u8 URL, it wroks and plays well.
 But the second one is buffering all the time , and I test it by ffmpeg , I get the same result.
You can try it by VLC or FFmpeg etc. It's the server side that goes wrong.
